export const DEFAULT_PROJECTS = [
  {
    id: 1,
    client: "Anytime Fitness",
    platform: "Instagram Reels",
    views: "1.2M",
    color: "#8E24AA",
    gradient: "from-purple-900/50 to-black",
    thumbnail: "/assets/projects/anytime-fitness.jpg",
    video: "/assets/projects/anytime-fitness.mp4",
    logo: "/assets/projects/anytime-fitness-logo.jpg",
    logoLink: "https://www.instagram.com/anytimefitnessin?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id: 2,
    client: "Sharma Ji Ke Bhature",
    platform: "Instagram Reels",
    views: "3.4M",
    color: "#FFD43B",
    gradient: "from-yellow-900/50 to-black",
    thumbnail: "/assets/projects/skb-thumb.jpg",
    video: "/assets/projects/skb-video.mp4",
    logo: "/assets/projects/sharma-ke-bhature-logo.jpg",
    logoLink: "https://www.instagram.com/sharmajikebhature?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id: 3,
    client: "Global Holidays",
    platform: "YouTube Shorts",
    views: "1.2M",
    color: "#2A9D8F",
    gradient: "from-teal-900/50 to-black",
    thumbnail: "/assets/projects/global-holidays-thumb.jpg",
    video: "/assets/projects/global-holidays-video.mp4",
    logo: "/assets/projects/global-holidays-logo.png",
    logoLink: "https://www.instagram.com/globalholidays_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id: 4,
    client: "Make Your Trip Possible",
    platform: "TikTok Campaign",
    views: "2.4M",
    color: "#F4A261",
    gradient: "from-orange-900/50 to-black",
    thumbnail: "/assets/projects/make-your-trip-possible.jpg",
    video: "/assets/projects/make-your-trips-possible.mp4",
    logo: "/assets/projects/make-your-trip-possible-logo.jpg",
    logoLink: "https://www.instagram.com/makeyourtrippossible?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id: 5,
    client: "FOF Fitness",
    platform: "Instagram Reels",
    views: "1.2M",
    color: "#E63946",
    gradient: "from-red-900/50 to-black",
    thumbnail: "/assets/projects/fof-fitness.png",
    video: "/assets/projects/fof-fitness.mp4",
    logo: "/assets/projects/fof-fitness-logo.jpeg",
    logoLink: "https://www.instagram.com/fof_fitness?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id: 6,
    client: "Radhey Krishna Jewellers",
    platform: "Product Launch",
    views: "1.5M",
    color: "#7209B7",
    gradient: "from-purple-900/50 to-black",
    thumbnail: "/assets/projects/radhe-krishna-thumb.jpg",
    video: "/assets/projects/radhe-krishna-video.mp4",
    logo: "/assets/projects/radhe-krishna-logo.jpg",
    logoLink: "https://www.instagram.com/shri_radhey_krishna_jewellers?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id: 7,
    client: "VDMC",
    platform: "Event Promo",
    views: "980K",
    color: "#4361EE",
    gradient: "from-blue-900/50 to-black",
    thumbnail: "/assets/projects/vdmc-thumb.png",
    video: "/assets/projects/vdmc.mp4",
    logo: "/assets/projects/vdmc-logo.jpg",
    logoLink: "https://www.instagram.com/vdmc_official?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id: 8,
    client: "Career Launcher",
    platform: "Education Promo",
    views: "1.1M",
    color: "#3949AB",
    gradient: "from-indigo-900/50 to-black",
    thumbnail: "/assets/projects/career-launcher-thumb.jpg",
    video: "/assets/projects/career-launcher-video.mp4",
    logo: "/assets/projects/career-launcher-logo.jpg",
    logoLink: "https://www.instagram.com/careerlauncher?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id: 9,
    client: "Saral Gym",
    platform: "Instagram Reels",
    views: "2.3M",
    color: "#FF4D6D",
    gradient: "from-red-900/50 to-black",
    thumbnail: "/assets/projects/saral-gym-thumb.jpg",
    video: "/assets/projects/saral-gym.mp4",
    logo: "/assets/projects/saral-gym-logo.jpg",
    logoLink: "https://www.instagram.com/_saralgym_/",
  }
];

export const DEFAULT_FEEDBACK = [
  {
    title: "Poore India mein aag laga di!",
    quote: "Working with Viral Duo changed our entire perspective on marketing.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80",
    color: "#FF4D6D",
    feedback: "The level of creativity and strategic thinking is unmatched. Our brand is now recognized everywhere.",
    points: "Viral Content, Iconic Branding, ROI Focus",
    stars: "5"
  },
  {
    title: "Best decision for our growth.",
    quote: "Their cinematic approach captures attention instantly.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=80",
    color: "#4DB8E5",
    feedback: "If you want to go viral, this is the only team you should talk to.",
    points: "Strategic Storytelling, Market Dominance, Excellence",
    stars: "5"
  },
  {
    title: "Beyond our expectations.",
    quote: "Our engagement rates tripled in just one month.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=80",
    color: "#FFD43B",
    feedback: "Methodical analysis meets creative storytelling. We built an iconic identity with them.",
    points: "Engagement Mastery, Brand Authority, Result-Driven",
    stars: "5"
  },
  {
    title: "Engineering attention at its best.",
    quote: "They don't just post; they engineer results.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
    color: "#FFA726",
    feedback: "Our followers turned into a community. Impact is real and measurable.",
    points: "Precision Marketing, Creative Direction, Impact",
    stars: "5"
  }
];
